#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.StorageModel.Build
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WADLogs")]
	public partial class WADLogsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertWADWindowsEventLog(WADWindowsEventLog instance);
    partial void UpdateWADWindowsEventLog(WADWindowsEventLog instance);
    partial void DeleteWADWindowsEventLog(WADWindowsEventLog instance);
    partial void InsertWADLog(WADLog instance);
    partial void UpdateWADLog(WADLog instance);
    partial void DeleteWADLog(WADLog instance);
    partial void InsertWADDiagnosticInfrastructureLog(WADDiagnosticInfrastructureLog instance);
    partial void UpdateWADDiagnosticInfrastructureLog(WADDiagnosticInfrastructureLog instance);
    partial void DeleteWADDiagnosticInfrastructureLog(WADDiagnosticInfrastructureLog instance);
    partial void InsertWADDirectory(WADDirectory instance);
    partial void UpdateWADDirectory(WADDirectory instance);
    partial void DeleteWADDirectory(WADDirectory instance);
    partial void InsertWADIISLog(WADIISLog instance);
    partial void UpdateWADIISLog(WADIISLog instance);
    partial void DeleteWADIISLog(WADIISLog instance);
    partial void InsertWADIISFailedRequestLog(WADIISFailedRequestLog instance);
    partial void UpdateWADIISFailedRequestLog(WADIISFailedRequestLog instance);
    partial void DeleteWADIISFailedRequestLog(WADIISFailedRequestLog instance);
    #endregion
		
		public WADLogsDataContext() : 
				base("Data Source=.\\SQLEXPRESS;Initial Catalog=WADLogs;Integrated Security=True", mappingSource)
		{
			OnCreated();
		}
		
		public WADLogsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WADLogsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WADLogsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WADLogsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<WADWindowsEventLog> WADWindowsEventLogs
		{
			get
			{
				return this.GetTable<WADWindowsEventLog>();
			}
		}
		
		public System.Data.Linq.Table<WADLog> WADLogs
		{
			get
			{
				return this.GetTable<WADLog>();
			}
		}
		
		public System.Data.Linq.Table<WADDiagnosticInfrastructureLog> WADDiagnosticInfrastructureLogs
		{
			get
			{
				return this.GetTable<WADDiagnosticInfrastructureLog>();
			}
		}
		
		public System.Data.Linq.Table<WADDirectory> WADDirectories
		{
			get
			{
				return this.GetTable<WADDirectory>();
			}
		}
		
		public System.Data.Linq.Table<WADIISLog> WADIISLogs
		{
			get
			{
				return this.GetTable<WADIISLog>();
			}
		}
		
		public System.Data.Linq.Table<WADIISFailedRequestLog> WADIISFailedRequestLogs
		{
			get
			{
				return this.GetTable<WADIISFailedRequestLog>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WADWindowsEventLogs")]
	public partial class WADWindowsEventLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PartitionKey;
		
		private string _RowKey;
		
		private System.DateTime _Timestamp;
		
		private long _EventTickCount;
		
		private string _DeploymentId;
		
		private string _Role;
		
		private string _RoleInstance;
		
		private System.Guid _ProviderGuid;
		
		private string _ProviderName;
		
		private int _EventId;
		
		private int _Level;
		
		private int _Pid;
		
		private int _Tid;
		
		private string _Channel;
		
		private System.Xml.Linq.XElement _RawXml;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPartitionKeyChanging(string value);
    partial void OnPartitionKeyChanged();
    partial void OnRowKeyChanging(string value);
    partial void OnRowKeyChanged();
    partial void OnTimestampChanging(System.DateTime value);
    partial void OnTimestampChanged();
    partial void OnEventTickCountChanging(long value);
    partial void OnEventTickCountChanged();
    partial void OnDeploymentIdChanging(string value);
    partial void OnDeploymentIdChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnRoleInstanceChanging(string value);
    partial void OnRoleInstanceChanged();
    partial void OnProviderGuidChanging(System.Guid value);
    partial void OnProviderGuidChanged();
    partial void OnProviderNameChanging(string value);
    partial void OnProviderNameChanged();
    partial void OnEventIdChanging(int value);
    partial void OnEventIdChanged();
    partial void OnLevelChanging(int value);
    partial void OnLevelChanged();
    partial void OnPidChanging(int value);
    partial void OnPidChanged();
    partial void OnTidChanging(int value);
    partial void OnTidChanged();
    partial void OnChannelChanging(string value);
    partial void OnChannelChanged();
    partial void OnRawXmlChanging(System.Xml.Linq.XElement value);
    partial void OnRawXmlChanged();
    #endregion
		
		public WADWindowsEventLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartitionKey", DbType="VarChar(32) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PartitionKey
		{
			get
			{
				return this._PartitionKey;
			}
			set
			{
				if ((this._PartitionKey != value))
				{
					this.OnPartitionKeyChanging(value);
					this.SendPropertyChanging();
					this._PartitionKey = value;
					this.SendPropertyChanged("PartitionKey");
					this.OnPartitionKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowKey", DbType="VarChar(256) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RowKey
		{
			get
			{
				return this._RowKey;
			}
			set
			{
				if ((this._RowKey != value))
				{
					this.OnRowKeyChanging(value);
					this.SendPropertyChanging();
					this._RowKey = value;
					this.SendPropertyChanged("RowKey");
					this.OnRowKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", DbType="DateTime NOT NULL")]
		public System.DateTime Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventTickCount", DbType="BigInt NOT NULL")]
		public long EventTickCount
		{
			get
			{
				return this._EventTickCount;
			}
			set
			{
				if ((this._EventTickCount != value))
				{
					this.OnEventTickCountChanging(value);
					this.SendPropertyChanging();
					this._EventTickCount = value;
					this.SendPropertyChanged("EventTickCount");
					this.OnEventTickCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeploymentId", DbType="Char(32) NOT NULL", CanBeNull=false)]
		public string DeploymentId
		{
			get
			{
				return this._DeploymentId;
			}
			set
			{
				if ((this._DeploymentId != value))
				{
					this.OnDeploymentIdChanging(value);
					this.SendPropertyChanging();
					this._DeploymentId = value;
					this.SendPropertyChanged("DeploymentId");
					this.OnDeploymentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleInstance", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string RoleInstance
		{
			get
			{
				return this._RoleInstance;
			}
			set
			{
				if ((this._RoleInstance != value))
				{
					this.OnRoleInstanceChanging(value);
					this.SendPropertyChanging();
					this._RoleInstance = value;
					this.SendPropertyChanged("RoleInstance");
					this.OnRoleInstanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProviderGuid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ProviderGuid
		{
			get
			{
				return this._ProviderGuid;
			}
			set
			{
				if ((this._ProviderGuid != value))
				{
					this.OnProviderGuidChanging(value);
					this.SendPropertyChanging();
					this._ProviderGuid = value;
					this.SendPropertyChanged("ProviderGuid");
					this.OnProviderGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProviderName", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string ProviderName
		{
			get
			{
				return this._ProviderName;
			}
			set
			{
				if ((this._ProviderName != value))
				{
					this.OnProviderNameChanging(value);
					this.SendPropertyChanging();
					this._ProviderName = value;
					this.SendPropertyChanged("ProviderName");
					this.OnProviderNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventId", DbType="Int NOT NULL")]
		public int EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				if ((this._EventId != value))
				{
					this.OnEventIdChanging(value);
					this.SendPropertyChanging();
					this._EventId = value;
					this.SendPropertyChanged("EventId");
					this.OnEventIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Int NOT NULL")]
		public int Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this.OnLevelChanging(value);
					this.SendPropertyChanging();
					this._Level = value;
					this.SendPropertyChanged("Level");
					this.OnLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pid", DbType="Int NOT NULL")]
		public int Pid
		{
			get
			{
				return this._Pid;
			}
			set
			{
				if ((this._Pid != value))
				{
					this.OnPidChanging(value);
					this.SendPropertyChanging();
					this._Pid = value;
					this.SendPropertyChanged("Pid");
					this.OnPidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tid", DbType="Int NOT NULL")]
		public int Tid
		{
			get
			{
				return this._Tid;
			}
			set
			{
				if ((this._Tid != value))
				{
					this.OnTidChanging(value);
					this.SendPropertyChanging();
					this._Tid = value;
					this.SendPropertyChanged("Tid");
					this.OnTidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Channel", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Channel
		{
			get
			{
				return this._Channel;
			}
			set
			{
				if ((this._Channel != value))
				{
					this.OnChannelChanging(value);
					this.SendPropertyChanging();
					this._Channel = value;
					this.SendPropertyChanged("Channel");
					this.OnChannelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RawXml", DbType="Xml NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement RawXml
		{
			get
			{
				return this._RawXml;
			}
			set
			{
				if ((this._RawXml != value))
				{
					this.OnRawXmlChanging(value);
					this.SendPropertyChanging();
					this._RawXml = value;
					this.SendPropertyChanged("RawXml");
					this.OnRawXmlChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WADLogs")]
	public partial class WADLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PartitionKey;
		
		private string _RowKey;
		
		private System.DateTime _Timestamp;
		
		private long _EventTickCount;
		
		private string _DeploymentId;
		
		private string _Role;
		
		private string _RoleInstance;
		
		private int _Level;
		
		private int _EventId;
		
		private int _Pid;
		
		private int _Tid;
		
		private string _Message;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPartitionKeyChanging(string value);
    partial void OnPartitionKeyChanged();
    partial void OnRowKeyChanging(string value);
    partial void OnRowKeyChanged();
    partial void OnTimestampChanging(System.DateTime value);
    partial void OnTimestampChanged();
    partial void OnEventTickCountChanging(long value);
    partial void OnEventTickCountChanged();
    partial void OnDeploymentIdChanging(string value);
    partial void OnDeploymentIdChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnRoleInstanceChanging(string value);
    partial void OnRoleInstanceChanged();
    partial void OnLevelChanging(int value);
    partial void OnLevelChanged();
    partial void OnEventIdChanging(int value);
    partial void OnEventIdChanged();
    partial void OnPidChanging(int value);
    partial void OnPidChanged();
    partial void OnTidChanging(int value);
    partial void OnTidChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    #endregion
		
		public WADLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartitionKey", DbType="VarChar(32) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PartitionKey
		{
			get
			{
				return this._PartitionKey;
			}
			set
			{
				if ((this._PartitionKey != value))
				{
					this.OnPartitionKeyChanging(value);
					this.SendPropertyChanging();
					this._PartitionKey = value;
					this.SendPropertyChanged("PartitionKey");
					this.OnPartitionKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowKey", DbType="VarChar(256) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RowKey
		{
			get
			{
				return this._RowKey;
			}
			set
			{
				if ((this._RowKey != value))
				{
					this.OnRowKeyChanging(value);
					this.SendPropertyChanging();
					this._RowKey = value;
					this.SendPropertyChanged("RowKey");
					this.OnRowKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", DbType="DateTime NOT NULL")]
		public System.DateTime Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventTickCount", DbType="BigInt NOT NULL")]
		public long EventTickCount
		{
			get
			{
				return this._EventTickCount;
			}
			set
			{
				if ((this._EventTickCount != value))
				{
					this.OnEventTickCountChanging(value);
					this.SendPropertyChanging();
					this._EventTickCount = value;
					this.SendPropertyChanged("EventTickCount");
					this.OnEventTickCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeploymentId", DbType="Char(32) NOT NULL", CanBeNull=false)]
		public string DeploymentId
		{
			get
			{
				return this._DeploymentId;
			}
			set
			{
				if ((this._DeploymentId != value))
				{
					this.OnDeploymentIdChanging(value);
					this.SendPropertyChanging();
					this._DeploymentId = value;
					this.SendPropertyChanged("DeploymentId");
					this.OnDeploymentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleInstance", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string RoleInstance
		{
			get
			{
				return this._RoleInstance;
			}
			set
			{
				if ((this._RoleInstance != value))
				{
					this.OnRoleInstanceChanging(value);
					this.SendPropertyChanging();
					this._RoleInstance = value;
					this.SendPropertyChanged("RoleInstance");
					this.OnRoleInstanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Int NOT NULL")]
		public int Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this.OnLevelChanging(value);
					this.SendPropertyChanging();
					this._Level = value;
					this.SendPropertyChanged("Level");
					this.OnLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventId", DbType="Int NOT NULL")]
		public int EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				if ((this._EventId != value))
				{
					this.OnEventIdChanging(value);
					this.SendPropertyChanging();
					this._EventId = value;
					this.SendPropertyChanged("EventId");
					this.OnEventIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pid", DbType="Int NOT NULL")]
		public int Pid
		{
			get
			{
				return this._Pid;
			}
			set
			{
				if ((this._Pid != value))
				{
					this.OnPidChanging(value);
					this.SendPropertyChanging();
					this._Pid = value;
					this.SendPropertyChanged("Pid");
					this.OnPidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tid", DbType="Int NOT NULL")]
		public int Tid
		{
			get
			{
				return this._Tid;
			}
			set
			{
				if ((this._Tid != value))
				{
					this.OnTidChanging(value);
					this.SendPropertyChanging();
					this._Tid = value;
					this.SendPropertyChanged("Tid");
					this.OnTidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WADDiagnosticInfrastructureLogs")]
	public partial class WADDiagnosticInfrastructureLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PartitionKey;
		
		private string _RowKey;
		
		private System.DateTime _Timestamp;
		
		private long _EventTickCount;
		
		private string _DeploymentId;
		
		private string _Role;
		
		private string _RoleInstance;
		
		private int _Level;
		
		private int _Pid;
		
		private int _Tid;
		
		private string _Function;
		
		private int _Line;
		
		private int _MDRESULT;
		
		private int _ErrorCode;
		
		private string _ErrorCodeMsg;
		
		private string _Message;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPartitionKeyChanging(string value);
    partial void OnPartitionKeyChanged();
    partial void OnRowKeyChanging(string value);
    partial void OnRowKeyChanged();
    partial void OnTimestampChanging(System.DateTime value);
    partial void OnTimestampChanged();
    partial void OnEventTickCountChanging(long value);
    partial void OnEventTickCountChanged();
    partial void OnDeploymentIdChanging(string value);
    partial void OnDeploymentIdChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnRoleInstanceChanging(string value);
    partial void OnRoleInstanceChanged();
    partial void OnLevelChanging(int value);
    partial void OnLevelChanged();
    partial void OnPidChanging(int value);
    partial void OnPidChanged();
    partial void OnTidChanging(int value);
    partial void OnTidChanged();
    partial void OnFunctionChanging(string value);
    partial void OnFunctionChanged();
    partial void OnLineChanging(int value);
    partial void OnLineChanged();
    partial void OnMDRESULTChanging(int value);
    partial void OnMDRESULTChanged();
    partial void OnErrorCodeChanging(int value);
    partial void OnErrorCodeChanged();
    partial void OnErrorCodeMsgChanging(string value);
    partial void OnErrorCodeMsgChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    #endregion
		
		public WADDiagnosticInfrastructureLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartitionKey", DbType="VarChar(32) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PartitionKey
		{
			get
			{
				return this._PartitionKey;
			}
			set
			{
				if ((this._PartitionKey != value))
				{
					this.OnPartitionKeyChanging(value);
					this.SendPropertyChanging();
					this._PartitionKey = value;
					this.SendPropertyChanged("PartitionKey");
					this.OnPartitionKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowKey", DbType="VarChar(256) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RowKey
		{
			get
			{
				return this._RowKey;
			}
			set
			{
				if ((this._RowKey != value))
				{
					this.OnRowKeyChanging(value);
					this.SendPropertyChanging();
					this._RowKey = value;
					this.SendPropertyChanged("RowKey");
					this.OnRowKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", DbType="DateTime NOT NULL")]
		public System.DateTime Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventTickCount", DbType="BigInt NOT NULL")]
		public long EventTickCount
		{
			get
			{
				return this._EventTickCount;
			}
			set
			{
				if ((this._EventTickCount != value))
				{
					this.OnEventTickCountChanging(value);
					this.SendPropertyChanging();
					this._EventTickCount = value;
					this.SendPropertyChanged("EventTickCount");
					this.OnEventTickCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeploymentId", DbType="Char(32) NOT NULL", CanBeNull=false)]
		public string DeploymentId
		{
			get
			{
				return this._DeploymentId;
			}
			set
			{
				if ((this._DeploymentId != value))
				{
					this.OnDeploymentIdChanging(value);
					this.SendPropertyChanging();
					this._DeploymentId = value;
					this.SendPropertyChanged("DeploymentId");
					this.OnDeploymentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleInstance", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string RoleInstance
		{
			get
			{
				return this._RoleInstance;
			}
			set
			{
				if ((this._RoleInstance != value))
				{
					this.OnRoleInstanceChanging(value);
					this.SendPropertyChanging();
					this._RoleInstance = value;
					this.SendPropertyChanged("RoleInstance");
					this.OnRoleInstanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Int NOT NULL")]
		public int Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this.OnLevelChanging(value);
					this.SendPropertyChanging();
					this._Level = value;
					this.SendPropertyChanged("Level");
					this.OnLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pid", DbType="Int NOT NULL")]
		public int Pid
		{
			get
			{
				return this._Pid;
			}
			set
			{
				if ((this._Pid != value))
				{
					this.OnPidChanging(value);
					this.SendPropertyChanging();
					this._Pid = value;
					this.SendPropertyChanged("Pid");
					this.OnPidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tid", DbType="Int NOT NULL")]
		public int Tid
		{
			get
			{
				return this._Tid;
			}
			set
			{
				if ((this._Tid != value))
				{
					this.OnTidChanging(value);
					this.SendPropertyChanging();
					this._Tid = value;
					this.SendPropertyChanged("Tid");
					this.OnTidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Function]", Storage="_Function", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string Function
		{
			get
			{
				return this._Function;
			}
			set
			{
				if ((this._Function != value))
				{
					this.OnFunctionChanging(value);
					this.SendPropertyChanging();
					this._Function = value;
					this.SendPropertyChanged("Function");
					this.OnFunctionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Line", DbType="Int NOT NULL")]
		public int Line
		{
			get
			{
				return this._Line;
			}
			set
			{
				if ((this._Line != value))
				{
					this.OnLineChanging(value);
					this.SendPropertyChanging();
					this._Line = value;
					this.SendPropertyChanged("Line");
					this.OnLineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MDRESULT", DbType="Int NOT NULL")]
		public int MDRESULT
		{
			get
			{
				return this._MDRESULT;
			}
			set
			{
				if ((this._MDRESULT != value))
				{
					this.OnMDRESULTChanging(value);
					this.SendPropertyChanging();
					this._MDRESULT = value;
					this.SendPropertyChanged("MDRESULT");
					this.OnMDRESULTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorCode", DbType="Int NOT NULL")]
		public int ErrorCode
		{
			get
			{
				return this._ErrorCode;
			}
			set
			{
				if ((this._ErrorCode != value))
				{
					this.OnErrorCodeChanging(value);
					this.SendPropertyChanging();
					this._ErrorCode = value;
					this.SendPropertyChanged("ErrorCode");
					this.OnErrorCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorCodeMsg", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string ErrorCodeMsg
		{
			get
			{
				return this._ErrorCodeMsg;
			}
			set
			{
				if ((this._ErrorCodeMsg != value))
				{
					this.OnErrorCodeMsgChanging(value);
					this.SendPropertyChanging();
					this._ErrorCodeMsg = value;
					this.SendPropertyChanged("ErrorCodeMsg");
					this.OnErrorCodeMsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WADDirectories")]
	public partial class WADDirectory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PartitionKey;
		
		private string _RowKey;
		
		private System.DateTime _Timestamp;
		
		private long _EventTickCount;
		
		private string _DeploymentId;
		
		private string _Role;
		
		private string _RoleInstance;
		
		private string _AbsolutePath;
		
		private string _RelativePath;
		
		private string _Container;
		
		private string _RootDirectory;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPartitionKeyChanging(string value);
    partial void OnPartitionKeyChanged();
    partial void OnRowKeyChanging(string value);
    partial void OnRowKeyChanged();
    partial void OnTimestampChanging(System.DateTime value);
    partial void OnTimestampChanged();
    partial void OnEventTickCountChanging(long value);
    partial void OnEventTickCountChanged();
    partial void OnDeploymentIdChanging(string value);
    partial void OnDeploymentIdChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnRoleInstanceChanging(string value);
    partial void OnRoleInstanceChanged();
    partial void OnAbsolutePathChanging(string value);
    partial void OnAbsolutePathChanged();
    partial void OnRelativePathChanging(string value);
    partial void OnRelativePathChanged();
    partial void OnContainerChanging(string value);
    partial void OnContainerChanged();
    partial void OnRootDirectoryChanging(string value);
    partial void OnRootDirectoryChanged();
    #endregion
		
		public WADDirectory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartitionKey", DbType="VarChar(32) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PartitionKey
		{
			get
			{
				return this._PartitionKey;
			}
			set
			{
				if ((this._PartitionKey != value))
				{
					this.OnPartitionKeyChanging(value);
					this.SendPropertyChanging();
					this._PartitionKey = value;
					this.SendPropertyChanged("PartitionKey");
					this.OnPartitionKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowKey", DbType="VarChar(256) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RowKey
		{
			get
			{
				return this._RowKey;
			}
			set
			{
				if ((this._RowKey != value))
				{
					this.OnRowKeyChanging(value);
					this.SendPropertyChanging();
					this._RowKey = value;
					this.SendPropertyChanged("RowKey");
					this.OnRowKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", DbType="DateTime NOT NULL")]
		public System.DateTime Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventTickCount", DbType="BigInt NOT NULL")]
		public long EventTickCount
		{
			get
			{
				return this._EventTickCount;
			}
			set
			{
				if ((this._EventTickCount != value))
				{
					this.OnEventTickCountChanging(value);
					this.SendPropertyChanging();
					this._EventTickCount = value;
					this.SendPropertyChanged("EventTickCount");
					this.OnEventTickCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeploymentId", DbType="Char(32) NOT NULL", CanBeNull=false)]
		public string DeploymentId
		{
			get
			{
				return this._DeploymentId;
			}
			set
			{
				if ((this._DeploymentId != value))
				{
					this.OnDeploymentIdChanging(value);
					this.SendPropertyChanging();
					this._DeploymentId = value;
					this.SendPropertyChanged("DeploymentId");
					this.OnDeploymentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleInstance", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string RoleInstance
		{
			get
			{
				return this._RoleInstance;
			}
			set
			{
				if ((this._RoleInstance != value))
				{
					this.OnRoleInstanceChanging(value);
					this.SendPropertyChanging();
					this._RoleInstance = value;
					this.SendPropertyChanged("RoleInstance");
					this.OnRoleInstanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AbsolutePath", DbType="VarChar(260) NOT NULL", CanBeNull=false)]
		public string AbsolutePath
		{
			get
			{
				return this._AbsolutePath;
			}
			set
			{
				if ((this._AbsolutePath != value))
				{
					this.OnAbsolutePathChanging(value);
					this.SendPropertyChanging();
					this._AbsolutePath = value;
					this.SendPropertyChanged("AbsolutePath");
					this.OnAbsolutePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelativePath", DbType="VarChar(260) NOT NULL", CanBeNull=false)]
		public string RelativePath
		{
			get
			{
				return this._RelativePath;
			}
			set
			{
				if ((this._RelativePath != value))
				{
					this.OnRelativePathChanging(value);
					this.SendPropertyChanging();
					this._RelativePath = value;
					this.SendPropertyChanged("RelativePath");
					this.OnRelativePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Container", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Container
		{
			get
			{
				return this._Container;
			}
			set
			{
				if ((this._Container != value))
				{
					this.OnContainerChanging(value);
					this.SendPropertyChanging();
					this._Container = value;
					this.SendPropertyChanged("Container");
					this.OnContainerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RootDirectory", DbType="VarChar(260) NOT NULL", CanBeNull=false)]
		public string RootDirectory
		{
			get
			{
				return this._RootDirectory;
			}
			set
			{
				if ((this._RootDirectory != value))
				{
					this.OnRootDirectoryChanging(value);
					this.SendPropertyChanging();
					this._RootDirectory = value;
					this.SendPropertyChanged("RootDirectory");
					this.OnRootDirectoryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WADIISLogs")]
	public partial class WADIISLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PartitionKey;
		
		private string _RowKey;
		
		private System.DateTime _Timestamp;
		
		private long _EventTickCount;
		
		private string _DeploymentId;
		
		private string _Role;
		
		private string _RoleInstance;
		
		private string _IPAddress;
		
		private string _UserName;
		
		private string _ServiceName;
		
		private string _ServerName;
		
		private string _ServerIPAddress;
		
		private int _ServerPort;
		
		private string _Method;
		
		private string _URIStem;
		
		private string _URIQuery;
		
		private int _ProtocolStatus;
		
		private int _ProtocolSubStatus;
		
		private int _Win32Status;
		
		private long _BytesSent;
		
		private long _BytesReceived;
		
		private int _TimeTaken;
		
		private string _ProtocolVersion;
		
		private string _Host;
		
		private string _UserAgent;
		
		private string _Cookie;
		
		private string _Referrer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPartitionKeyChanging(string value);
    partial void OnPartitionKeyChanged();
    partial void OnRowKeyChanging(string value);
    partial void OnRowKeyChanged();
    partial void OnTimestampChanging(System.DateTime value);
    partial void OnTimestampChanged();
    partial void OnEventTickCountChanging(long value);
    partial void OnEventTickCountChanged();
    partial void OnDeploymentIdChanging(string value);
    partial void OnDeploymentIdChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnRoleInstanceChanging(string value);
    partial void OnRoleInstanceChanged();
    partial void OnIPAddressChanging(string value);
    partial void OnIPAddressChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnServiceNameChanging(string value);
    partial void OnServiceNameChanged();
    partial void OnServerNameChanging(string value);
    partial void OnServerNameChanged();
    partial void OnServerIPAddressChanging(string value);
    partial void OnServerIPAddressChanged();
    partial void OnServerPortChanging(int value);
    partial void OnServerPortChanged();
    partial void OnMethodChanging(string value);
    partial void OnMethodChanged();
    partial void OnURIStemChanging(string value);
    partial void OnURIStemChanged();
    partial void OnURIQueryChanging(string value);
    partial void OnURIQueryChanged();
    partial void OnProtocolStatusChanging(int value);
    partial void OnProtocolStatusChanged();
    partial void OnProtocolSubStatusChanging(int value);
    partial void OnProtocolSubStatusChanged();
    partial void OnWin32StatusChanging(int value);
    partial void OnWin32StatusChanged();
    partial void OnBytesSentChanging(long value);
    partial void OnBytesSentChanged();
    partial void OnBytesReceivedChanging(long value);
    partial void OnBytesReceivedChanged();
    partial void OnTimeTakenChanging(int value);
    partial void OnTimeTakenChanged();
    partial void OnProtocolVersionChanging(string value);
    partial void OnProtocolVersionChanged();
    partial void OnHostChanging(string value);
    partial void OnHostChanged();
    partial void OnUserAgentChanging(string value);
    partial void OnUserAgentChanged();
    partial void OnCookieChanging(string value);
    partial void OnCookieChanged();
    partial void OnReferrerChanging(string value);
    partial void OnReferrerChanged();
    #endregion
		
		public WADIISLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartitionKey", DbType="VarChar(32) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PartitionKey
		{
			get
			{
				return this._PartitionKey;
			}
			set
			{
				if ((this._PartitionKey != value))
				{
					this.OnPartitionKeyChanging(value);
					this.SendPropertyChanging();
					this._PartitionKey = value;
					this.SendPropertyChanged("PartitionKey");
					this.OnPartitionKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowKey", DbType="VarChar(256) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RowKey
		{
			get
			{
				return this._RowKey;
			}
			set
			{
				if ((this._RowKey != value))
				{
					this.OnRowKeyChanging(value);
					this.SendPropertyChanging();
					this._RowKey = value;
					this.SendPropertyChanged("RowKey");
					this.OnRowKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", DbType="DateTime NOT NULL")]
		public System.DateTime Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventTickCount", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long EventTickCount
		{
			get
			{
				return this._EventTickCount;
			}
			set
			{
				if ((this._EventTickCount != value))
				{
					this.OnEventTickCountChanging(value);
					this.SendPropertyChanging();
					this._EventTickCount = value;
					this.SendPropertyChanged("EventTickCount");
					this.OnEventTickCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeploymentId", DbType="Char(32) NOT NULL", CanBeNull=false)]
		public string DeploymentId
		{
			get
			{
				return this._DeploymentId;
			}
			set
			{
				if ((this._DeploymentId != value))
				{
					this.OnDeploymentIdChanging(value);
					this.SendPropertyChanging();
					this._DeploymentId = value;
					this.SendPropertyChanged("DeploymentId");
					this.OnDeploymentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleInstance", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string RoleInstance
		{
			get
			{
				return this._RoleInstance;
			}
			set
			{
				if ((this._RoleInstance != value))
				{
					this.OnRoleInstanceChanging(value);
					this.SendPropertyChanging();
					this._RoleInstance = value;
					this.SendPropertyChanged("RoleInstance");
					this.OnRoleInstanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPAddress", DbType="VarChar(16)")]
		public string IPAddress
		{
			get
			{
				return this._IPAddress;
			}
			set
			{
				if ((this._IPAddress != value))
				{
					this.OnIPAddressChanging(value);
					this.SendPropertyChanging();
					this._IPAddress = value;
					this.SendPropertyChanged("IPAddress");
					this.OnIPAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(16)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceName", DbType="VarChar(16)")]
		public string ServiceName
		{
			get
			{
				return this._ServiceName;
			}
			set
			{
				if ((this._ServiceName != value))
				{
					this.OnServiceNameChanging(value);
					this.SendPropertyChanging();
					this._ServiceName = value;
					this.SendPropertyChanged("ServiceName");
					this.OnServiceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServerName", DbType="VarChar(16)")]
		public string ServerName
		{
			get
			{
				return this._ServerName;
			}
			set
			{
				if ((this._ServerName != value))
				{
					this.OnServerNameChanging(value);
					this.SendPropertyChanging();
					this._ServerName = value;
					this.SendPropertyChanged("ServerName");
					this.OnServerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServerIPAddress", DbType="VarChar(16)")]
		public string ServerIPAddress
		{
			get
			{
				return this._ServerIPAddress;
			}
			set
			{
				if ((this._ServerIPAddress != value))
				{
					this.OnServerIPAddressChanging(value);
					this.SendPropertyChanging();
					this._ServerIPAddress = value;
					this.SendPropertyChanged("ServerIPAddress");
					this.OnServerIPAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServerPort", DbType="Int NOT NULL")]
		public int ServerPort
		{
			get
			{
				return this._ServerPort;
			}
			set
			{
				if ((this._ServerPort != value))
				{
					this.OnServerPortChanging(value);
					this.SendPropertyChanging();
					this._ServerPort = value;
					this.SendPropertyChanged("ServerPort");
					this.OnServerPortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Method", DbType="VarChar(8)")]
		public string Method
		{
			get
			{
				return this._Method;
			}
			set
			{
				if ((this._Method != value))
				{
					this.OnMethodChanging(value);
					this.SendPropertyChanging();
					this._Method = value;
					this.SendPropertyChanged("Method");
					this.OnMethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URIStem", DbType="VarChar(1024)")]
		public string URIStem
		{
			get
			{
				return this._URIStem;
			}
			set
			{
				if ((this._URIStem != value))
				{
					this.OnURIStemChanging(value);
					this.SendPropertyChanging();
					this._URIStem = value;
					this.SendPropertyChanged("URIStem");
					this.OnURIStemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URIQuery", DbType="VarChar(1024)")]
		public string URIQuery
		{
			get
			{
				return this._URIQuery;
			}
			set
			{
				if ((this._URIQuery != value))
				{
					this.OnURIQueryChanging(value);
					this.SendPropertyChanging();
					this._URIQuery = value;
					this.SendPropertyChanged("URIQuery");
					this.OnURIQueryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProtocolStatus", DbType="Int NOT NULL")]
		public int ProtocolStatus
		{
			get
			{
				return this._ProtocolStatus;
			}
			set
			{
				if ((this._ProtocolStatus != value))
				{
					this.OnProtocolStatusChanging(value);
					this.SendPropertyChanging();
					this._ProtocolStatus = value;
					this.SendPropertyChanged("ProtocolStatus");
					this.OnProtocolStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProtocolSubStatus", DbType="Int NOT NULL")]
		public int ProtocolSubStatus
		{
			get
			{
				return this._ProtocolSubStatus;
			}
			set
			{
				if ((this._ProtocolSubStatus != value))
				{
					this.OnProtocolSubStatusChanging(value);
					this.SendPropertyChanging();
					this._ProtocolSubStatus = value;
					this.SendPropertyChanged("ProtocolSubStatus");
					this.OnProtocolSubStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Win32Status", DbType="Int NOT NULL")]
		public int Win32Status
		{
			get
			{
				return this._Win32Status;
			}
			set
			{
				if ((this._Win32Status != value))
				{
					this.OnWin32StatusChanging(value);
					this.SendPropertyChanging();
					this._Win32Status = value;
					this.SendPropertyChanged("Win32Status");
					this.OnWin32StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BytesSent", DbType="BigInt NOT NULL")]
		public long BytesSent
		{
			get
			{
				return this._BytesSent;
			}
			set
			{
				if ((this._BytesSent != value))
				{
					this.OnBytesSentChanging(value);
					this.SendPropertyChanging();
					this._BytesSent = value;
					this.SendPropertyChanged("BytesSent");
					this.OnBytesSentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BytesReceived", DbType="BigInt NOT NULL")]
		public long BytesReceived
		{
			get
			{
				return this._BytesReceived;
			}
			set
			{
				if ((this._BytesReceived != value))
				{
					this.OnBytesReceivedChanging(value);
					this.SendPropertyChanging();
					this._BytesReceived = value;
					this.SendPropertyChanged("BytesReceived");
					this.OnBytesReceivedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeTaken", DbType="Int NOT NULL")]
		public int TimeTaken
		{
			get
			{
				return this._TimeTaken;
			}
			set
			{
				if ((this._TimeTaken != value))
				{
					this.OnTimeTakenChanging(value);
					this.SendPropertyChanging();
					this._TimeTaken = value;
					this.SendPropertyChanged("TimeTaken");
					this.OnTimeTakenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProtocolVersion", DbType="VarChar(8)")]
		public string ProtocolVersion
		{
			get
			{
				return this._ProtocolVersion;
			}
			set
			{
				if ((this._ProtocolVersion != value))
				{
					this.OnProtocolVersionChanging(value);
					this.SendPropertyChanging();
					this._ProtocolVersion = value;
					this.SendPropertyChanged("ProtocolVersion");
					this.OnProtocolVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Host", DbType="VarChar(32)")]
		public string Host
		{
			get
			{
				return this._Host;
			}
			set
			{
				if ((this._Host != value))
				{
					this.OnHostChanging(value);
					this.SendPropertyChanging();
					this._Host = value;
					this.SendPropertyChanged("Host");
					this.OnHostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserAgent", DbType="VarChar(1024)")]
		public string UserAgent
		{
			get
			{
				return this._UserAgent;
			}
			set
			{
				if ((this._UserAgent != value))
				{
					this.OnUserAgentChanging(value);
					this.SendPropertyChanging();
					this._UserAgent = value;
					this.SendPropertyChanged("UserAgent");
					this.OnUserAgentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cookie", DbType="VarChar(1024)")]
		public string Cookie
		{
			get
			{
				return this._Cookie;
			}
			set
			{
				if ((this._Cookie != value))
				{
					this.OnCookieChanging(value);
					this.SendPropertyChanging();
					this._Cookie = value;
					this.SendPropertyChanged("Cookie");
					this.OnCookieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Referrer", DbType="VarChar(1024)")]
		public string Referrer
		{
			get
			{
				return this._Referrer;
			}
			set
			{
				if ((this._Referrer != value))
				{
					this.OnReferrerChanging(value);
					this.SendPropertyChanging();
					this._Referrer = value;
					this.SendPropertyChanged("Referrer");
					this.OnReferrerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WADIISFailedRequestLogs")]
	public partial class WADIISFailedRequestLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PartitionKey;
		
		private string _RowKey;
		
		private System.DateTime _Timestamp;
		
		private long _EventTickCount;
		
		private string _DeploymentId;
		
		private string _Role;
		
		private string _RoleInstance;
		
		private string _Url;
		
		private System.Guid _AppPoolId;
		
		private int _Pid;
		
		private string _Verb;
		
		private string _RemoteUserName;
		
		private string _UserName;
		
		private string _AuthenticationType;
		
		private int _StatusCode;
		
		private System.Nullable<int> _SubStatusCode;
		
		private int _TimeTaken;
		
		private System.Xml.Linq.XElement _RawXml;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPartitionKeyChanging(string value);
    partial void OnPartitionKeyChanged();
    partial void OnRowKeyChanging(string value);
    partial void OnRowKeyChanged();
    partial void OnTimestampChanging(System.DateTime value);
    partial void OnTimestampChanged();
    partial void OnEventTickCountChanging(long value);
    partial void OnEventTickCountChanged();
    partial void OnDeploymentIdChanging(string value);
    partial void OnDeploymentIdChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnRoleInstanceChanging(string value);
    partial void OnRoleInstanceChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OnAppPoolIdChanging(System.Guid value);
    partial void OnAppPoolIdChanged();
    partial void OnPidChanging(int value);
    partial void OnPidChanged();
    partial void OnVerbChanging(string value);
    partial void OnVerbChanged();
    partial void OnRemoteUserNameChanging(string value);
    partial void OnRemoteUserNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnAuthenticationTypeChanging(string value);
    partial void OnAuthenticationTypeChanged();
    partial void OnStatusCodeChanging(int value);
    partial void OnStatusCodeChanged();
    partial void OnSubStatusCodeChanging(System.Nullable<int> value);
    partial void OnSubStatusCodeChanged();
    partial void OnTimeTakenChanging(int value);
    partial void OnTimeTakenChanged();
    partial void OnRawXmlChanging(System.Xml.Linq.XElement value);
    partial void OnRawXmlChanged();
    #endregion
		
		public WADIISFailedRequestLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartitionKey", DbType="VarChar(32) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PartitionKey
		{
			get
			{
				return this._PartitionKey;
			}
			set
			{
				if ((this._PartitionKey != value))
				{
					this.OnPartitionKeyChanging(value);
					this.SendPropertyChanging();
					this._PartitionKey = value;
					this.SendPropertyChanged("PartitionKey");
					this.OnPartitionKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowKey", DbType="VarChar(256) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RowKey
		{
			get
			{
				return this._RowKey;
			}
			set
			{
				if ((this._RowKey != value))
				{
					this.OnRowKeyChanging(value);
					this.SendPropertyChanging();
					this._RowKey = value;
					this.SendPropertyChanged("RowKey");
					this.OnRowKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", DbType="DateTime NOT NULL")]
		public System.DateTime Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventTickCount", DbType="BigInt NOT NULL")]
		public long EventTickCount
		{
			get
			{
				return this._EventTickCount;
			}
			set
			{
				if ((this._EventTickCount != value))
				{
					this.OnEventTickCountChanging(value);
					this.SendPropertyChanging();
					this._EventTickCount = value;
					this.SendPropertyChanged("EventTickCount");
					this.OnEventTickCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeploymentId", DbType="Char(32) NOT NULL", CanBeNull=false)]
		public string DeploymentId
		{
			get
			{
				return this._DeploymentId;
			}
			set
			{
				if ((this._DeploymentId != value))
				{
					this.OnDeploymentIdChanging(value);
					this.SendPropertyChanging();
					this._DeploymentId = value;
					this.SendPropertyChanged("DeploymentId");
					this.OnDeploymentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleInstance", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string RoleInstance
		{
			get
			{
				return this._RoleInstance;
			}
			set
			{
				if ((this._RoleInstance != value))
				{
					this.OnRoleInstanceChanging(value);
					this.SendPropertyChanging();
					this._RoleInstance = value;
					this.SendPropertyChanged("RoleInstance");
					this.OnRoleInstanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppPoolId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid AppPoolId
		{
			get
			{
				return this._AppPoolId;
			}
			set
			{
				if ((this._AppPoolId != value))
				{
					this.OnAppPoolIdChanging(value);
					this.SendPropertyChanging();
					this._AppPoolId = value;
					this.SendPropertyChanged("AppPoolId");
					this.OnAppPoolIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pid", DbType="Int NOT NULL")]
		public int Pid
		{
			get
			{
				return this._Pid;
			}
			set
			{
				if ((this._Pid != value))
				{
					this.OnPidChanging(value);
					this.SendPropertyChanging();
					this._Pid = value;
					this.SendPropertyChanged("Pid");
					this.OnPidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Verb", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Verb
		{
			get
			{
				return this._Verb;
			}
			set
			{
				if ((this._Verb != value))
				{
					this.OnVerbChanging(value);
					this.SendPropertyChanging();
					this._Verb = value;
					this.SendPropertyChanged("Verb");
					this.OnVerbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemoteUserName", DbType="VarChar(16)")]
		public string RemoteUserName
		{
			get
			{
				return this._RemoteUserName;
			}
			set
			{
				if ((this._RemoteUserName != value))
				{
					this.OnRemoteUserNameChanging(value);
					this.SendPropertyChanging();
					this._RemoteUserName = value;
					this.SendPropertyChanged("RemoteUserName");
					this.OnRemoteUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(16)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthenticationType", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string AuthenticationType
		{
			get
			{
				return this._AuthenticationType;
			}
			set
			{
				if ((this._AuthenticationType != value))
				{
					this.OnAuthenticationTypeChanging(value);
					this.SendPropertyChanging();
					this._AuthenticationType = value;
					this.SendPropertyChanged("AuthenticationType");
					this.OnAuthenticationTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusCode", DbType="Int NOT NULL")]
		public int StatusCode
		{
			get
			{
				return this._StatusCode;
			}
			set
			{
				if ((this._StatusCode != value))
				{
					this.OnStatusCodeChanging(value);
					this.SendPropertyChanging();
					this._StatusCode = value;
					this.SendPropertyChanged("StatusCode");
					this.OnStatusCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubStatusCode", DbType="Int")]
		public System.Nullable<int> SubStatusCode
		{
			get
			{
				return this._SubStatusCode;
			}
			set
			{
				if ((this._SubStatusCode != value))
				{
					this.OnSubStatusCodeChanging(value);
					this.SendPropertyChanging();
					this._SubStatusCode = value;
					this.SendPropertyChanged("SubStatusCode");
					this.OnSubStatusCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeTaken", DbType="Int NOT NULL")]
		public int TimeTaken
		{
			get
			{
				return this._TimeTaken;
			}
			set
			{
				if ((this._TimeTaken != value))
				{
					this.OnTimeTakenChanging(value);
					this.SendPropertyChanging();
					this._TimeTaken = value;
					this.SendPropertyChanged("TimeTaken");
					this.OnTimeTakenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RawXml", DbType="Xml NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement RawXml
		{
			get
			{
				return this._RawXml;
			}
			set
			{
				if ((this._RawXml != value))
				{
					this.OnRawXmlChanging(value);
					this.SendPropertyChanging();
					this._RawXml = value;
					this.SendPropertyChanged("RawXml");
					this.OnRawXmlChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
