//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Topian System")]
[assembly: AssemblyProduct("cloud4net")]
[assembly: AssemblyCopyright("Copyright © 2009-2011 Topian System")]
[assembly: AssemblyTrademark("The MIT License (MIT) - http://cloud4net.codeplex.com/license ")]
[assembly: AssemblyVersion("1.0.12.43352")]
[assembly: AssemblyFileVersion("1.0.12.43352")]


